const symbols = [
  {
    button: 0,
    eng: ["`", "~"],
    engName: ["`", "~"],
    rus: ["ё", "Ё"],
    rusName: ["Ё"],
    all: ["`", "~", "ё", "Ё"],
  },
  {
    button: 1,
    eng: ["1", "!"],
    rus: ["1", "!"],
    all: ["1", "!"],
  },
  {
    button: 2,
    eng: ["2", "@"],
    rus: ["2", '"'],
    all: ["2", "@", '"'],
  },
  {
    button: 3,
    eng: ["3", "#"],
    rus: ["3", "№"],
    all: ["3", "#", "№"],
  },
  {
    button: 4,
    eng: ["4", "$"],
    rus: ["4", ";"],
    all: ["4", "$", ";"],
  },
  {
    button: 5,
    eng: ["5", "%"],
    rus: ["5", "%"],
    all: ["5", "%"],
  },
  {
    button: 6,
    eng: ["6", "^"],
    rus: ["6", ":"],
    all: ["6", "^", ":"],
  },
  {
    button: 7,
    eng: ["7", "&"],
    rus: ["7", "?"],
    all: ["7", "&", "?"],
  },
  {
    button: 8,
    eng: ["8", "*"],
    rus: ["8", "*"],
    all: ["8", "*"],
  },
  {
    button: 9,
    eng: ["9", "("],
    rus: ["9", "("],
    all: ["9", "("],
  },
  {
    button: 10,
    eng: ["0", ")"],
    rus: ["0", ")"],
    all: ["0", ")"],
  },
  {
    button: 11,
    eng: ["-", "_"],
    rus: ["-", "_"],
    all: ["-", "_"],
  },
  {
    button: 12,
    eng: ["=", "+"],
    rus: ["=", "+"],
    all: ["=", "+"],
  },
  {
    button: 13,
    eng: ["Backspace", "Backspace"],
    rus: ["Backspace", "Backspace"],
    all: ["Backspace"],
  },
  {
    button: 14,
    eng: ["Tab", "Tab"],
    rus: ["Tab", "Tab"],
    all: ["Tab"],
  },
  {
    button: 15,
    eng: ["q", "Q"],
    rus: ["й", "Й"],
    all: ["q", "Q", "й", "Й"],
  },
  {
    button: 16,
    eng: ["w", "W"],
    rus: ["ц", "Ц"],
    all: ["w", "W", "ц", "Ц"],
  },
  {
    button: 17,
    eng: ["e", "E"],
    rus: ["у", "У"],
    all: ["e", "E", "у", "У"],
  },
  {
    button: 18,
    eng: ["r", "R"],
    rus: ["к", "К"],
    all: ["r", "R", "к", "К"],
  },
  {
    button: 19,
    eng: ["t", "T"],
    rus: ["е", "Е"],
    all: ["t", "T", "е", "Е"],
  },
  {
    button: 20,
    eng: ["y", "Y"],
    rus: ["н", "Н"],
    all: ["y", "Y", "н", "Н"],
  },
  {
    button: 21,
    eng: ["u", "U"],
    rus: ["г", "Г"],
    all: ["u", "U", "г", "Г"],
  },
  {
    button: 22,
    eng: ["i", "I"],
    rus: ["ш", "Ш"],
    all: ["i", "I", "ш", "Ш"],
  },
  {
    button: 23,
    eng: ["o", "O"],
    rus: ["щ", "Щ"],
    all: ["o", "O", "щ", "Щ"],
  },
  {
    button: 24,
    eng: ["p", "P"],
    rus: ["з", "З"],
    all: ["p", "P", "з", "З"],
  },
  {
    button: 25,
    eng: ["[", "{"],
    rus: ["х", "Х"],
    all: ["[", "{", "х", "Х"],
  },
  {
    button: 26,
    eng: ["]", "}"],
    rus: ["ъ", "Ъ"],
    all: ["]", "}", "ъ", "Ъ"],
  },
  {
    button: 27,
    eng: ["\\", "}"],
    rus: ["\\", "/"],
    all: ["\\", "|", "\\", "/"],
  },
  {
    button: 28,
    eng: ["Delete", "Delete"],
    rus: ["Delete", "Delete"],
    all: ["Delete"],
  },
  {
    button: 29,
    eng: ["Caps lock", "Caps lock"],
    rus: ["Caps lock", "Caps lock"],
    all: ["CapsLock"],
  },
  {
    button: 30,
    eng: ["a", "A"],
    rus: ["ф", "Ф"],
    all: ["a", "A", "ф", "Ф"],
  },
  {
    button: 31,
    eng: ["s", "S"],
    rus: ["ы", "Ы"],
    all: ["s", "S", "ы", "Ы"],
  },
  {
    button: 32,
    eng: ["d", "D"],
    rus: ["в", "В"],
    all: ["d", "D", "в", "В"],
  },
  {
    button: 33,
    eng: ["f", "F"],
    rus: ["а", "А"],
    all: ["f", "F", "а", "А"],
  },
  {
    button: 34,
    eng: ["g", "G"],
    rus: ["п", "П"],
    all: ["g", "G", "п", "П"],
  },
  {
    button: 35,
    eng: ["h", "H"],
    rus: ["р", "Р"],
    all: ["h", "H", "р", "Р"],
  },
  {
    button: 36,
    eng: ["j", "J"],
    rus: ["о", "О"],
    all: ["j", "J", "о", "О"],
  },
  {
    button: 37,
    eng: ["k", "K"],
    rus: ["л", "Л"],
    all: ["k", "K", "л", "Л"],
  },
  {
    button: 38,
    eng: ["l", "L"],
    rus: ["д", "Д"],
    all: ["l", "L", "д", "Д"],
  },
  {
    button: 39,
    eng: [";", ":"],
    rus: ["ж", "Ж"],
    all: [";", ":", "ж", "Ж"],
  },
  {
    button: 40,
    eng: ["'", '"'],
    rus: ["э", "Э"],
    all: ["'", '"', "э", "Э"],
  },
  {
    button: 41,
    eng: ["Enter", "Enter"],
    rus: ["Enter", "Enter"],
    all: ["Enter"],
  },
  {
    button: 42,
    code: ["ShiftLeft"],
    eng: ["Shift", "Shift"],
    rus: ["Shift", "Shift"],
    all: ["Shift"],
  },
  {
    button: 43,
    eng: ["z", "Z"],
    rus: ["я", "Я"],
    all: ["z", "Z", "я", "Я"],
  },
  {
    button: 44,
    eng: ["x", "X"],
    rus: ["ч", "Ч"],
    all: ["x", "X", "ч", "Ч"],
  },
  {
    button: 45,
    eng: ["c", "C"],
    rus: ["с", "С"],
    all: ["c", "C", "с", "С"],
  },
  {
    button: 46,
    eng: ["v", "V"],
    rus: ["м", "М"],
    all: ["v", "V", "м", "М"],
  },
  {
    button: 47,
    eng: ["b", "B"],
    rus: ["и", "И"],
    all: ["b", "B", "и", "И"],
  },
  {
    button: 48,
    eng: ["n", "N"],
    rus: ["т", "Т"],
    all: ["n", "N", "т", "Т"],
  },
  {
    button: 49,
    eng: ["m", "M"],
    rus: ["ь", "Ь"],
    all: ["m", "M", "ь", "Ь"],
  },
  {
    button: 50,
    eng: [",", "<"],
    rus: ["б", "Б"],
    all: [",", "<", "б", "Б"],
  },
  {
    button: 51,
    eng: [".", ">"],
    rus: ["ю", "Ю"],
    all: [".", ">", "ю", "Ю"],
  },
  {
    button: 52,
    eng: ["/", "?"],
    rus: [".", ","],
    all: ["/", "?", ".", ","],
  },
  {
    button: 53,
    eng: ["", ""],
    rus: ["", ""],
    all: ["ArrowUp"],
  },
  {
    button: 54,
    code: ["ShiftRight"],
    eng: ["Shift", "Shift"],
    rus: ["Shift", "Shift"],
    all: ["Shift"],
  },
  {
    button: 55,
    code: ["ControlLeft"],
    eng: ["Ctrl", "Ctrl"],
    rus: ["Ctrl", "Ctrl"],
    all: ["Control"],
  },
  {
    button: 56,
    eng: ["Win", "Win"],
    rus: ["Win", "Win"],
    all: ["Meta"],
  },
  {
    button: 57,
    code: ["AltLeft"],
    eng: ["Alt", "Alt"],
    rus: ["Alt", "Alt"],
    all: ["Alt"],
  },
  {
    button: 58,
    code: ["Space"],
    eng: ["-----", "-----"],
    rus: ["-----", "-----"],
    all: [" "],
  },
  {
    button: 59,
    code: ["AltRight"],
    eng: ["Alt", "Alt"],
    rus: ["Alt", "Alt"],
    all: ["AltGraph"],
  },
  {
    button: 60,
    eng: ["", ""],
    rus: ["", ""],
    all: ["ArrowLeft"],
  },
  {
    button: 61,
    eng: ["", ""],
    rus: ["", ""],
    all: ["ArrowDown"],
  },
  {
    button: 62,
    eng: ["", ""],
    rus: ["", ""],
    all: ["ArrowRight"],
  },
  {
    button: 63,
    code: ["ControlRight"],
    eng: ["Ctrl", "Ctrl"],
    rus: ["Ctrl", "Ctrl"],
    all: ["Control"],
  },
];
export default symbols;
